schema_version = "1.0.0"

id = "unexpectedslicer_airtable"
version = "1.0.0"
name = "Unexpectedslicer_airtable"
tagline = "UnexpectedSlicer to Airtable"
maintainer = "Nicolas Predella"
type = "add-on"


tags = ["Import-Export"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-2.0-or-later",
]
platforms = [
    "windows-x64",
    "macos-arm64",
    "linux-x64"
]
wheels = [
    "./wheels/requests-2.32.3-py3-none-any.whl",
    "./wheels/pyairtable-3.2.0-py2.py3-none-any.whl"
]
copyright = []

[permissions]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "experimental/",
  "cache/",
]