schema_version = "1.0.0"

id = "unexpectedslicer_airtable"
version = "1.0.0"
name = "Unexpectedslicer_airtable"
tagline = "UnexpectedSlicer to Airtable"
maintainer = "Nicolas Predella"
type = "add-on"


tags = ["Import-Export"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-2.0-or-later",
]